import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import FontAswesomeConfig from "./fontawesome";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Bindok Thoughts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
         <FontAswesomeConfig/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <div>TopNav</div> */}
            {children}
          {/* <div>Footer</div> */}
      </body>
    </html>
  );
}
